module.exports.review_Validation = require("./review.validation")
module.exports.comment_Validation = require("./comment.validation")
module.exports.tag_Validation = require("./tag.validation")
module.exports.blog_Validation = require("./blog.validation")
module.exports.invoice_Validation = require("./invoice.validation")
module.exports.payment_Validation = require("./payment.validation")
module.exports.employee_Validation = require("./employee.validation")
module.exports.supplier_Validation = require("./supplier.validation")
module.exports.buyer_Validation = require("./buyer.validation")
module.exports.customer_Validation = require("./customer.validation")

module.exports.inventory_Validation = require("./inventory.validation")
module.exports.recipe_Validation = require("./recipe.validation")
module.exports.event_Validation = require("./event.validation")
module.exports.ticket_Validation = require("./ticket.validation")
module.exports.subscription_Validation = require("./subscription.validation")
module.exports.vehicle_Validation = require("./vehicle.validation")
module.exports.rental_Validation = require("./rental.validation")
module.exports.forum_Validation = require("./forum.validation")
module.exports.poll_Validation = require("./poll.validation")
module.exports.survey_Validation = require("./survey.validation")


module.exports.sport_Validation = require("./sport.name.validation.js")
module.exports.sport_founder_Validation = require("./sport.founder.validation")
module.exports.sport_contact_Validation = require("./sport.contact.validation")
module.exports.sport_gallery_Validation = require("./sport.gallery.validation")
module.exports.sport_team_Validation = require("./sport.team.validation")
module.exports.sport_category_Validation = require("./sport.category.validation")
module.exports.sport_player_Validation = require("./sport.player.validation")
module.exports.sport_coach_Validation = require("./sport.coach.validation")
module.exports.sport_event_Validation = require("./sport.event.validation")
module.exports.sport_result_Validation = require("./sport.result.validation")
module.exports.sport_news_Validation = require("./sport.news.validation")

module.exports.crypto_Validation = require("./crypto.name.validation")
module.exports.crypto_founder_Validation = require("./crypto.founder.validation")
module.exports.crypto_type_Validation = require("./crypto.type.validation")
module.exports.crypto_rating_Validation = require("./crypto.rating.validation")
module.exports.crypto_faq_Validation = require("./crypto.faq.validation")
module.exports.crypto_link_Validation = require("./crypto.link.validation")
module.exports.crypto_client_Validation = require("./crypto.client.validation")
module.exports.crypto_calendar_Validation = require("./crypto.calendar.validation")
module.exports.crypto_news_Validation = require("./crypto.news.validation")
module.exports.crypto_newsletter_Validation = require("./crypto.newsletter.validation")
module.exports.crypto_potential_Validation = require("./crypto.potential.validation")